version: "1.0"

provider:
  name: openfaas
  gateway: http://34.38.245.109:8080

functions:
  authentication:
    lang: docker
    handler: ./authenticate_user
    image: chtaybo22/authentication:latest
    environment:
      write_debug: true

  create-account-secure:
    lang: docker
    handler: ./create-user
    image: chtaybo22/create-account-secure:latest

  generate-2fa:
    lang: docker
    handler: ./generate_2fa
    image: chtaybo22/generate-2fa:latest
    environment:
      write_debug: true

  generate-password:
    lang: docker
    handler: ./generate_password
    image: chtaybo22/generate-password:latest
    environment:
      write_timeout: 30s
      read_timeout: 30s
      exec_timeout: 30s

  verify-2fa:
    lang: docker
    handler: ./verify-2fa
    image: chtaybo22/verify-2fa:latest
    environment:
      write_debug: true
