FROM python:3.10-slim

WORKDIR /function

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

ENV fprocess="python index.py"
CMD ["fwatchdog"]

# OpenFaaS watchdog
RUN apt-get update && apt-get install -y curl
RUN curl -sSL https://github.com/openfaas/of-watchdog/releases/latest/download/of-watchdog > /usr/bin/fwatchdog && \
    chmod +x /usr/bin/fwatchdog

HEALTHCHECK --interval=3s CMD [ -e /tmp/.lock ] || exit 1
